server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: Edris
    url: jdbc:postgresql://localhost:5432/Employees
    password: database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
